<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 https://maven.apache.org/xsd/maven-4.0.0.xsd">
    <modelVersion>4.0.0</modelVersion>

    <groupId>cn.hdfk7</groupId>
    <artifactId>hdfk7-boot</artifactId>
    <version>${revision}</version>
    <packaging>pom</packaging>
    <name>hdfk7-boot</name>

    <properties>
        <maven.deploy.skip>true</maven.deploy.skip>
    </properties>

    <modules>
        <module>boot/hdfk7-boot-parent</module>
        <module>boot/hdfk7-boot-proto</module>
        <module>boot/hdfk7-boot-starter-code-generator</module>
        <module>boot/hdfk7-boot-starter-common</module>
        <module>boot/hdfk7-boot-starter-discovery</module>
        <module>example</module>
    </modules>
</project>
